model_path:
  large: "models/mistral-7b-instruct-v0.1.Q8_0.gguf" #mention the path to your ai model from hugging face 

model_type: "mistral"

model_config: {'max_new_tokens': 512, 'temperature': 0,'context_length': 4096,'gpu_layers': 0}

embeddings_path: "BAAI/bge-large-en-v1.5"

chat_history_path: "chat_sessions/"

